version = '2'

[linters]
enable = [
  'errchkjson',
  'gocognit',
  'goconst',
  'gocritic',
  'gocyclo',
  'maintidx',
  'misspell',
  'mnd',
  'nakedret',
  'prealloc',
  'revive',
  'thelper',
  'tparallel',
  'unconvert',
  'unparam',
  'usestdlibvars',
  'wrapcheck'
]

[linters.settings]
[linters.settings.gocognit]
min-complexity = 15

[linters.settings.gocyclo]
min-complexity = 15

[linters.settings.revive]
[[linters.settings.revive.rules]]
name = 'package-comments'
disabled = true

[linters.settings.wrapcheck]
ignore-package-globs = [
  'github.com/eljamo/mempass/*'
]

[linters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
enable = [
  'gci',
  'gofumpt',
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
