builds:
  - id: mempass-cli
    main: ./main.go
    binary: mempass
    goos:
#      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
     - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

#universal_binaries:
#  - replace: true

checksum:
  name_template: 'checksums.txt'