version: 2
builds:
  - id: mempass-cli
    main: ./main.go
    binary: mempass
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

checksum:
  name_template: "checksums.txt"
